<%
  require 'fileutils'
  project_name = 'fest'
  path = FileUtils.pwd.split('/')
  database_name = (path[-2] == "releases") ? path[-3].gsub('.','_') : path[-1]
%>
development:
  adapter: mysql
  database: <%= database_name %>_development
  username: <%= project_name %>
  password: <%= project_name %>
  #encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: <%= database_name %>_test
  username: <%= project_name %>
  password: <%= project_name %>
  #encoding: utf8
  database: fest_test
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

benchmarking:
  adapter: mysql
  database: <%= database_name %>_development
  username: <%= project_name %>
  password: <%= project_name %>
  #encoding: utf8
  database: fest_development
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

stage:
  adapter: mysql
  database: <%= project_name %>_stage
  username: <%= project_name %>
  password: <%= project_name %>
  #encoding: utf8
  database: fest_stage
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: <%= project_name %>_production
  username: <%= project_name %>
  password: <%= project_name %>
  #encoding: utf8
  database: fest_production
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
